### ISSUE TITLE
Error running Update.sh

### ISSUE THREAD

**Issue by 2Dman** [Altitude-Tech/Sensly#11]
sudo sh Update.sh 

gives me the following error:

Traceback (most recent call last):
  File "stm32loader.py", line 427, in <module>
    cmd.open(conf['port'], conf['baud'])
  File "stm32loader.py", line 71, in open
    timeout=5               # set a timeout value, None for waiting forever
  File "/usr/lib/python2.7/dist-packages/serial/serialutil.py", line 236, in __init__
    self.open()
  File "/usr/lib/python2.7/dist-packages/serial/serialposix.py", line 272, in open
    self._reconfigure_port(force_update=True)
  File "/usr/lib/python2.7/dist-packages/serial/serialposix.py", line 315, in _reconfigure_port
    raise SerialException("Could not configure port: {}".format(msg))
serial.serialutil.SerialException: Could not configure port: (5, 'Input/output error')
Can't init. Ensure that BOOT0 is enabled and reset device
Traceback (most recent call last):
  File "stm32loader.py", line 436, in <module>
    bootversion = cmd.cmdGet()
  File "stm32loader.py", line 118, in cmdGet
    if self.cmdGeneric(0x00):
  File "stm32loader.py", line 115, in cmdGeneric
    return self._wait_for_ask(hex(cmd))
  File "stm32loader.py", line 80, in _wait_for_ask
    raise CmdException("Can't read port or timeout")
__main__.CmdException: Can't read port or timeout

**Comment by phgachoud** [comment]
Closed, please refer to https://github.com/Altitude-Tech/Sensly_install project !
