### ISSUE TITLE
Sensor.py Remote I/O Error from Dust Sensor (Sharp GP2Y10 14 7218)

### ISSUE THREAD

**Issue by phgachoud** [Altitude-Tech/Sensly#6]
Opening the next issue, when calling Sensly.py It crashes on a readbyte, already tried to reset the GPIO before but does not solve the problem. 

```
pi@Pi2: ~/Sensly$ python Sensly.py
2017-11-06 15:58:07.191 DEBUG Sensly - <module>: Writting data to ./Sensly_06-11-2017_15_58_07.csv
2017-11-06 15:58:07.193 INFO Sensly - <module>: Sensly is warming up please wait for 1 seconds
2017-11-06 15:58:08.195 INFO Sensly - <module>: Heating Completed
2017-11-06 15:58:08.196 INFO Sensly - <module>: Enterring to a True loop, Ctrl+c to stop it...
2017-11-06 15:58:11.381 DEBUG Sensly - <module>: Trying to get informations from particules meter
Traceback (most recent call last):
  File "Sensly.py", line 333, in <module>
    pmData = PM.Get_PMDensity(PMcmd)
  File "/home/pi/dev/sensly_HAT_airQltySensor/Sensly/Sensors.py", line 83, in Get_PMDensity
    self.Get_PMVolt(cmd)
  File "/home/pi/dev/sensly_HAT_airQltySensor/Sensly/Sensors.py", line 78, in Get_PMVolt
    self.PMVolt = ((3300.00/self.MaxADC)*float(self.Get_rawdata(cmd))*11.00)
  File "/home/pi/dev/sensly_HAT_airQltySensor/Sensly/Sensors.py", line 48, in Get_rawdata
    data.append(self._device.read_byte(I2C_Addr))
IOError: [Errno 121] Remote I/O error

```

**Comment by phgachoud** [comment]
@samAlti What did you modify into the base Adafruit BME280 driver? do you remember? comparing them is too difficult there were too many changes. My idea is to use the Adafruit one, it seems you only use the read_temperature & read_humidity into it. What do you say?

For the moment its crashing into the init  sometimes & read_temperature for sure (from your bme_combo.py file)

**Comment by phgachoud** [comment]
Increased counter between write & readbyte on dust sensor, but getting 15, 255 as data always, the produced results after your calculations seem false...
`cat Sensly_07-11-2017_22_36_00.csv
Time, Carbon Monoxide PPM, Ammonia PPM, Carbon Dioxide PPM, Methly PPM, Acetone PPM, Methane PPM, LPG PPM, Hydrogen PPM, Propane PPM, PM10 
22:36:01,0,0,0,0,0,0,0,0,0,7160.0
22:36:15,0,0,0,0,0,0,0,0,0,7160.0
22:36:29,0,0,0,0,0,0,0,0,0,7160.0
22:36:43,0,0,0,0,0,0,0,0,0,7160.0
22:36:57,0,0,0,0,0,0,0,0,0,7160.0
22:37:11,0,0,0,0,0,0,0,0,0,7160.0
22:37:24,0,0,0,0,0,0,0,0,0,7160.0
` please help me...

**Comment by phgachoud** [comment]
seems that this person has same problem... https://forum.dexterindustries.com/t/interacting-with-a-sharp-gp2y1010-dust-sensor/1878

**Comment by phgachoud** [comment]
I/O Error disappeared so closing the issue, even if I don't know if the data are correct...

**Comment by gesaleh** [comment]
@phgachoud thank for your update 
I'll try to keep up with the modifications, where i can pull the new files I'll do some testing and if i can contribute I'll try to 

Thanks
BTW my update.sh never worked
