### ISSUE TITLE
Does the HAT actually work?

### ISSUE THREAD

**Issue by ferazambuja** [Altitude-Tech/Sensly#9]
Did anyone was ever able to get it to work?
I just got mine from Altitude. From the lack of support here, it's a shame that they still sell it.

**Comment by phgachoud** [comment]
It's not the case from my part! Actually yes in my opinion its a shame they continue to sell it!!!

@frazer-altitude @samAlti : Please change your politics and stop selling something you tell its working and its not the case! Have a little ethics or dedicate some time to solve the software problems!!!

**Comment by 2Dman** [comment]
same here,when running:
sudo python Sensly.py 
2018-04-11 19:02:25.433 DEBUG Sensly - init_BME280_Sensor: ----- BME Sensor {}
2018-04-11 19:02:25.435 INFO Sensly - <module>: You can check your data into ./sampleData/Sensly_%d-%m-%Y_%H_%M_%S.csv
Traceback (most recent call last):
  File "Sensly.py", line 518, in <module>
    init_BME280_Sensor()
  File "Sensly.py", line 102, in init_BME280_Sensor
    bME280_Sensor = Adafruit_BME280.BME280(t_mode=Adafruit_BME280.BME280_OSAMPLE_8, h_mode=Adafruit_BME280.BME280_OSAMPLE_8, address=0x76) # Sometimes Crash with a connection timeout
  File "/home/pi/sensly/Sensly/Adafruit_BME280.py", line 127, in __init__
    import Adafruit_GPIO.I2C as I2C
ImportError: No module named Adafruit_GPIO.I2C

**Comment by duchenef** [comment]
Same for me. Can't even follow the basic tutorial (http://www.instructables.com/id/Sensly-Hat-for-the-Raspberry-Pi-Air-Quality-Gas-De/): crontab doens't work, can shift from calib mode to normal mode, calibration usually crashess after a few minutes. The best I've had was with phgachoud's fork, from which I managed to get "some" data after calibrating and entering the R0 data in Sensly.py... disappointing. Next thing I'm trying is to install the hat on a Pi2 instead of a Pi3...

**Comment by phgachoud** [comment]
@duchenef you're loosing your time, the scripts do not work, the PI model doesn't affect that... P2 and P3 have the same problem as you can see in different posts of issues on this project. Try my [latest version](https://github.com/phgachoud/Sensly/tree/sensors_tests) if you want to get some datas...

**Comment by ferazambuja** [comment]
I'm quite disappointed and surprise that they are even introducing new ones. I decided to get an extra 3B+ just to play with. Now I get kernel panic after I install...
On my other pi I get the zeros...was also never able to flash the STM32(DFU mode) with the ./update.sh

Isn't there any other standalone libraries around that could work?
If there was more info about the shield specifications. Mine is version 1.1.

Altitude never replies my emails...I gave up on returning.

**Comment by phgachoud** [comment]
@ferazambuja It seems that this HAT was built for AltitudeTech, to play more, you could see other libs for the separated sensors, addressing them with the respective sensors addresses (I documented a bit in Sensly.py). @ least see what the complex received data from sensors means, We really are in electronics low level with these sensors. The Idea of AltitudeTech was good I think, but it seems they documented bad what they did, so I'm unable to understand whats done without taking the whole documentation of the separated sensors and try to understand what is really done. More than that, we'd have to have a lab to be able to test every gas, I personnaly dont have those gases @ home ;-)
Again... the only thing I could do is giving you [this link](https://github.com/phgachoud/Sensly -> branch sensors_tests) which contains the things I've done till now. Seems we have to work with that as an opensource project where all the people complaining it doesn't work do a part to document and fix the issues. I'll start with getting datas and document what the existing scripts seem to do. I let a doc directory into my branch which contains doc about the sensors... enjoy! ;-)

**Comment by ferazambuja** [comment]
@2Dman You need to install the Adafruit GPIO library for the BME280. https://github.com/adafruit/Adafruit_Python_BME280  

@phgachoud Thanks for all your help. I'm checking the documentation. I'm running your code and it works. I will compare my log with yours.

**Comment by phgachoud** [comment]
@ferazambuja see logging for that type of things, you could add a logger which adds the results to a log file. Actually for the moment I only configured the logger to Sensly.log into current directory. You could just grep this file if you are using linux.... `grep -a 'Raw Data' Sensly.log` otherwise, you can add them to a separate file, but its not the goal of best practices of logging as I conceive it... What do you think?

**Comment by duchenef** [comment]
@phgachoud , Ok thank you, I didn't waste more time trying difference Pi models. However I found on Alt Tech's website a raspbian image on which clibration (or seemed to) worked well. But from there I could not update to normal mode (Can't init. Ensure that Boot0 is enabled and reset device). If I simply add my R0 values to Sensly.py, the script only returns 0 values (7160 for PM10)... I guess you're right, the whole Sensly.py script is rubbish, and someone will probably have to redo the job from scratch starting from the sensors' datasheets...

**Comment by ferazambuja** [comment]
@duchenef the Boot0 is a message that the script failed to upload the firmware (Sensly.binary) to the  STM32F072 (https://www.mouser.com/datasheet/2/389/stm32f072c8-956183.pdf) on the Sensly board. When you run the update.sh it puts the board on DFU mode waiting for the firmware. However, the upload script always fails. 

If your sensly has a USB port you can actually see the STM32 in DFU mode using the dfu-util (http://dfu-util.sourceforge.net) or the STM bootloader.

I have no idea what is in the binary file or even if this board comes flashed from the factory. It's another mystery that @frazer-altitude @samAlti could help us understand.

The STM32 could be working as an ADC for the gas sensors and the Sharp GP2Y10 and be the culprit of the zero error.

There is some new files on the Sensly Install repo. I'm going to try them out.

**Comment by ferazambuja** [comment]
At least their spam server works:/ offering me a discount on another non-functional HAT. They could at least tell us to move on... @frazer-altitude @samAlti 

[ https://imgur.com/a/sMZs08b](url)
